"""photo_analysis zengin alanlar

Revision ID: b05ab8dd4e2f
Revises: 921dfba930d5
Create Date: 2026-07-31 17:32:00.012034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b05ab8dd4e2f'
down_revision: Union[str, Sequence[str], None] = '921dfba930d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo_analysis', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('photo_analysis', sa.Column('environment_type', sa.String(), nullable=True))
    op.add_column('photo_analysis', sa.Column('primary_object', sa.String(), nullable=True))
    op.add_column('photo_analysis', sa.Column('secondary_objects', postgresql.ARRAY(sa.String()), nullable=True, server_default='{}'))
    op.add_column('photo_analysis', sa.Column('attributes', postgresql.ARRAY(sa.String()), nullable=True, server_default='{}'))
    op.add_column('photo_analysis', sa.Column('action', sa.String(), nullable=True))
    op.add_column('photo_analysis', sa.Column('mood', sa.String(), nullable=True))
    op.add_column('photo_analysis', sa.Column('use_case', sa.String(), nullable=True))
    op.add_column('photo_analysis', sa.Column('context', postgresql.ARRAY(sa.String()), nullable=True, server_default='{}'))
    op.add_column('photo_analysis', sa.Column('style', postgresql.ARRAY(sa.String()), nullable=True, server_default='{}'))
    op.add_column('photo_analysis', sa.Column('audience', postgresql.ARRAY(sa.String()), nullable=True, server_default='{}'))
    op.add_column('photo_analysis', sa.Column('public_figures', postgresql.JSONB(astext_type=sa.Text()), nullable=True, server_default=sa.text("'[]'::jsonb")))
    op.add_column('photo_analysis', sa.Column('all_tags', postgresql.ARRAY(sa.String()), nullable=True, server_default='{}'))
    op.drop_column('photo_analysis', 'summary')
    op.drop_column('photo_analysis', 'activity')
    op.drop_column('photo_analysis', 'caption')
    # ### end Alembic commands ###

    # autogenerate 'environment' kolonundaki tip degisimini (String -> ARRAY(String))
    # yakalamadi -- eski environment (indoor/outdoor/mixed) ile yeni environment
    # (mekan/ortam etiketleri listesi) ayni isimde ama tamamen farkli anlamlar
    # tasidigindan cast yerine drop+yeniden ekleme tercih edildi. Eski
    # environment_type karsiligi zaten yeni environment_type kolonuna tasindi.
    op.drop_column('photo_analysis', 'environment')
    op.add_column('photo_analysis', sa.Column('environment', postgresql.ARRAY(sa.String()), nullable=True, server_default='{}'))


def downgrade() -> None:
    """Downgrade schema."""
    # environment: yeni ARRAY(String) kolonunu kaldirip eski String kolonunu geri getir.
    op.drop_column('photo_analysis', 'environment')
    op.add_column('photo_analysis', sa.Column('environment', sa.String(), autoincrement=False, nullable=True))

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo_analysis', sa.Column('caption', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('photo_analysis', sa.Column('activity', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('photo_analysis', sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('photo_analysis', 'all_tags')
    op.drop_column('photo_analysis', 'public_figures')
    op.drop_column('photo_analysis', 'audience')
    op.drop_column('photo_analysis', 'style')
    op.drop_column('photo_analysis', 'context')
    op.drop_column('photo_analysis', 'use_case')
    op.drop_column('photo_analysis', 'mood')
    op.drop_column('photo_analysis', 'action')
    op.drop_column('photo_analysis', 'attributes')
    op.drop_column('photo_analysis', 'secondary_objects')
    op.drop_column('photo_analysis', 'primary_object')
    op.drop_column('photo_analysis', 'environment_type')
    op.drop_column('photo_analysis', 'description')
    # ### end Alembic commands ###
